[package]
name = "kak-loli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
once_cell = "1.8.0"
regex = "1.5.4"
serde = "1.0.130"
structopt = "0.3.23"
thiserror = "1.0.29"
